# Generated by Django 3.2.2 on 2021-07-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=255, null=True)),
                ('Status', models.TextField(max_length=100, null=True)),
                ('Address', models.TextField(max_length=100, null=True)),
            ],
        ),
    ]
